### ISSUE TITLE
Conda environment setup

### ISSUE THREAD

**Issue by sufiah59** [gutfeeling/realdeeprl#1]
Hi Dibya, can you help me on these error while setting up the conda environment?:

After running these codes for windows: "(real_world_deep_rl_course) C:\Users\user>conda env update --name real_world_deep_rl_course --file environment.yml "

I have these error: 

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3367, in _dep_map
    return self.__dep_map
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3147, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_parser.py", line 215, in _parse_specifier
    tokenizer.consume("WS")
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_tokenizer.py", line 189, in enclosing_tokens
    self.raise_syntax_error(
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    opencv-python (>=3.) ; extra == 'all'
                  ~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 247, in iter_dependencies
    return self._dist.requires(extras)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3070, in requires
    dm = self._dep_map
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3369, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3379, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3434, in __init__
    super().__init__(requirement_string)
  File "C:\Users\user\miniconda3\envs\real_world_deep_rl_course\lib\site-packages\pip\_vendor\packaging\requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    opencv-python (>=3.) ; extra == 'all'
                  ~~~~^

failed

CondaEnvException: Pip failed

**Comment by gutfeeling** [comment]
It's hard to tell from this error message.

Are you sure you are using the environment file provided in the repo?

The error suggests an issue with a malformed dependency specification in
the environment.yml file. Specifically, it looks like there is a problem
with how the opencv-python package is listed in the dependencies.

However, the environment file in the repo does not explicitly require
opencv-python.

So please first verify if the right environment file is being used.

I can look into this further if that doesn't help, but my availability
currently is a bit limited. ChatGPT is your friend.
